"""Sweet Tea custom node pack entrypoint.

Exposes all bundled nodes from a single registry package.
"""

if __package__:
    from .usdu_pose_tiled import (
        NODE_CLASS_MAPPINGS as USDU_NODE_CLASS_MAPPINGS,
        NODE_DISPLAY_NAME_MAPPINGS as USDU_NODE_DISPLAY_NAME_MAPPINGS,
    )
    from .wan_vace_caps_inpaint import (
        NODE_CLASS_MAPPINGS as WAN_CAPS_NODE_CLASS_MAPPINGS,
        NODE_DISPLAY_NAME_MAPPINGS as WAN_CAPS_NODE_DISPLAY_NAME_MAPPINGS,
    )
    from .wan_vace_hybrid_subject import (
        NODE_CLASS_MAPPINGS as WAN_HYBRID_NODE_CLASS_MAPPINGS,
        NODE_DISPLAY_NAME_MAPPINGS as WAN_HYBRID_NODE_DISPLAY_NAME_MAPPINGS,
    )
else:
    try:
        from usdu_pose_tiled import (
            NODE_CLASS_MAPPINGS as USDU_NODE_CLASS_MAPPINGS,
            NODE_DISPLAY_NAME_MAPPINGS as USDU_NODE_DISPLAY_NAME_MAPPINGS,
        )
        from wan_vace_caps_inpaint import (
            NODE_CLASS_MAPPINGS as WAN_CAPS_NODE_CLASS_MAPPINGS,
            NODE_DISPLAY_NAME_MAPPINGS as WAN_CAPS_NODE_DISPLAY_NAME_MAPPINGS,
        )
        from wan_vace_hybrid_subject import (
            NODE_CLASS_MAPPINGS as WAN_HYBRID_NODE_CLASS_MAPPINGS,
            NODE_DISPLAY_NAME_MAPPINGS as WAN_HYBRID_NODE_DISPLAY_NAME_MAPPINGS,
        )
    except ImportError:
        USDU_NODE_CLASS_MAPPINGS = {}
        USDU_NODE_DISPLAY_NAME_MAPPINGS = {}
        WAN_CAPS_NODE_CLASS_MAPPINGS = {}
        WAN_CAPS_NODE_DISPLAY_NAME_MAPPINGS = {}
        WAN_HYBRID_NODE_CLASS_MAPPINGS = {}
        WAN_HYBRID_NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(USDU_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(WAN_CAPS_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(WAN_HYBRID_NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(USDU_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(WAN_CAPS_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(WAN_HYBRID_NODE_DISPLAY_NAME_MAPPINGS)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
