"""Sweet Tea custom node pack entrypoint.

Exposes all bundled nodes from a single registry package.
"""

from .usdu_pose_tiled import (
    NODE_CLASS_MAPPINGS as USDU_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as USDU_NODE_DISPLAY_NAME_MAPPINGS,
)
from .wan_vace_caps_inpaint import (
    NODE_CLASS_MAPPINGS as WAN_CAPS_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as WAN_CAPS_NODE_DISPLAY_NAME_MAPPINGS,
)
from .wan_vace_dual_strength import (
    NODE_CLASS_MAPPINGS as WAN_DUAL_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as WAN_DUAL_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(USDU_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(WAN_CAPS_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(WAN_DUAL_NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(USDU_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(WAN_CAPS_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(WAN_DUAL_NODE_DISPLAY_NAME_MAPPINGS)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
